### ISSUE TITLE
The Roadmap

### ISSUE THREAD

**Issue by UlisesGascon** [UlisesGascon/express-examples#1]
### Context

https://github.com/expressjs/express/issues/5309

### Roadmap
- [x] Cleanup branches
- [x] Cleanup releases/tags
- [x] Add support for NVM https://github.com/UlisesGascon/express-examples/pull/4
- [x] Rename the repo and the metadata associated https://github.com/UlisesGascon/express-examples/pull/2
- [x] Remove the express core stuff and install express as a dependency https://github.com/UlisesGascon/express-examples/pull/5
- [x] Update the CI to use Current/LTS Node.js versions only https://github.com/UlisesGascon/express-examples/pull/3
- [x] Update the Documentation https://github.com/UlisesGascon/express-examples/pull/6
- [x] Rename principal branch to `main`
- [ ] Migrate this repo to expressjs Org as `expressjs/examples` https://github.com/expressjs/express/issues/5309#issuecomment-1806872713

### Notes

- Cherry pick commits from other forks: https://stackoverflow.com/a/11477795 
- Delete all tags (remote and local): https://www.abhith.net/snippets/git/delete-all-local-remote-git-tags/
